name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment: 
      name: testing
    env:
      database_hostname: ${{secrets.database_hostname}}
      database_port: ${{secrets.DATABASE_PORT}} 
      database_password: ${{secrets.DATABASE_PASSWORD}} 
      database_name: ${{secrets.DATABASE_NAME}} 
      database_username: ${{secrets.DATABASE_USERNAME}} 
      secret_key: ${{secrets.SECRET_KEY}} 
      algorith: ${{secrets.ALGORITH}} 
      access_token_expire_minutes: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}} 

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest
          
