name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env: 
      database_hostname: localhost
      database_port: 5432
      database_password: dhisdat
      database_name: fastapi
      database_username: postgres
      secret_key: 09we786251evgf3987efbjkdw0v9c8svnkl689431n0ffu04n4134h3r34r4g4091h
      algorith: HS256
      access_token_expire_minutes: 60

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest
          
